### ISSUE TITLE
prusa_mini_home_assistant is not a valid add-on repository

### ISSUE THREAD

**Issue by A-Bertelsen** [sq3tle/prusa_mini_home_assistant#1]
**Describe the bug**
I'm getting an error when I try to add "https://github.com/sq3tle/prusa_mini_home_assistant" into Custom repositories in Home assistant

**To Reproduce**
1. Supervisor -> Add-on Store -> Manage add-on repositories
2. add repository: "https://github.com/sq3tle/prusa_mini_home_assistant"
3. Error "Not a valid add-on repository"

**Expected behavior**
I expected to have the add on available to install

**Server:**
 - HA: 0.113.1
 - Raspi 4

**Error from system log**
`20-11-23 09:03:17 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/sq3tle/prusa_mini_home_assistant repository`
`20-11-23 09:03:18 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/fdae3219/repository.json: [Errno 2] No such file or directory: '/data/addons/git/fdae3219/repository.json'`
`20-11-23 09:03:18 ERROR (MainThread) [supervisor.store] https://github.com/sq3tle/prusa_mini_home_assistant is not a valid add-on repository. `
`20-11-23 09:03:18 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/sq3tle/prusa_mini_home_assistant`

**Comment by sq3tle** [comment]
Supervisor can't install this package, you need to install it via HACS (Home Assistant Community Store) or install this manualy.
