### ISSUE TITLE
Error: No 'version' key in the manifest file for custom integration 'prusa_connect'

### ISSUE THREAD

**Issue by A-Bertelsen** [sq3tle/prusa_mini_home_assistant#5]
**Is your feature request related to a problem? Please describe.**
I am getting an error on Home assistant (core-2021.4.3, supervisor-2021.03.9)
"No 'version' key in the manifest file for custom integration 'prusa_connect'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'prusa_connect'"

**Describe the solution you'd like**
I would like the error to be solved before "Home Assistant 2021.6" Since I like the use this addon

**Additional context**
The error code said to report this to the maintainer of 'prusa_connect'

**Comment by sq3tle** [comment]
HA decided to require this field in lastest version. Fixed in  1.4a release.
Thanks for reporting the issue :)

**Comment by caiosweet** [comment]
Maybe the version format is not right :0(
```WARNING (MainThread) [homeassistant.loader] '1.4a' is not a valid version for custom integration 'prusa_connect'. Please report this to the maintainer of 'prusa_connect'```
