### ISSUE TITLE
Unique id

### ISSUE THREAD

**Issue by ZD4ve** [sq3tle/prusa_mini_home_assistant#7]
**Is your feature request related to a problem? Please describe.**
Can't add area to sensors in the UI because they don't have a unique id.

**Describe the solution you'd like**
Generate unique id for the sensors.

**Describe alternatives you've considered**

**Additional context**
![IMG_20211224_012428](https://user-images.githubusercontent.com/69498757/147301625-91d67acd-44fc-45bc-b9ff-31d098da38e3.jpg)

**Comment by sq3tle** [comment]
You have an existing sensor entity under this name from another integration or plugin. This is specific to your HA instance. 
You have to identify and uninstall colliding plugin.
